paths:
  log: ./runs
  data:
    train: ${hydra:runtime.cwd}/data/external/train
    val: ${hydra:runtime.cwd}/data/external/valid
    test: ${hydra:runtime.cwd}/data/external/test
params:
  epochs: 1
  seed: 42
  train_loader:
    batch_size: 32
    shuffle: True
    num_workers: 4
    pin_memory: False
    drop_last: True
  val_loader:
    batch_size: 32
    shuffle: False
    num_workers: 4
    pin_memory: False
    drop_last: False
  test_loader:
    batch_size: 32
    shuffle: False
    num_workers: 4
    pin_memory: False
    drop_last: False
  model:
    name: swin_tiny_patch4_window7_224
    output_dim: 1
  optimizer:
    name: optim.AdamW
    params:
      lr: 1e-5
  scheduler:
    name: optim.lr_scheduler.CosineAnnealingWarmRestarts
    params:
      T_0: 20
      eta_min: 1e-4
  loss: nn.NLLLoss
  trainer:
    gpus: 0,
    # accumulate_grad_batches: 1,
    # fast_dev_run: False,
    # num_sanity_val_steps: 0,
    # resume_from_checkpoint: None
